### ISSUE TITLE
CC-by-sa license, for inclusion in Open Source projects?

### ISSUE THREAD

**Issue by joshtriplett** [hoeflerco/proofs#2]
Thank you for your careful and detailed work providing this sample text for evaluating fonts.

My first thought, upon reading it, was that it would make great sample text for inclusion in programs that preview fonts, such as operating-system font selection dialogues or previewers. Many of these either display the name of the font itself (rarely a representative sample), or the "quick brown fox" pangram.

Would you consider making the sample text (just the text, not the PDFs or similar) available under a CC-by-sa license, so that they could be included in Open Source projects like this?

**Comment by Jonathan-Hoefler** [comment]
Hi Josh,

Thanks for the kind words. I'd be happy to discuss this if you have a specific project in mind — please feel free to drop me a line!

Kindest Regards,

Jonathan
